### ISSUE TITLE
Tests with openjdk-8 failed

### ISSUE THREAD

**Issue by xiaodaxia** [bazaarvoice/jersey-hmac-auth#45]
When I run "mvn clean install", The output is as follows(only copy the failed output):

Running com.bazaarvoice.auth.hmac.client.HmacClientFilterTest
java.lang.Exception: Invalid signature
        at com.bazaarvoice.auth.hmac.client.SignatureValidatingHttpServer.validate(SignatureValidatingHttpServer.java:28)
        at com.bazaarvoice.auth.hmac.client.ValidatingHttpServer.handle(ValidatingHttpServer.java:50)
        at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121)
        at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: Invalid signature
        at com.bazaarvoice.auth.hmac.client.SignatureValidatingHttpServer.validate(SignatureValidatingHttpServer.java:28)
        at com.bazaarvoice.auth.hmac.client.ValidatingHttpServer.handle(ValidatingHttpServer.java:50)
        at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121)
        at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: Invalid signature
        at com.bazaarvoice.auth.hmac.client.SignatureValidatingHttpServer.validate(SignatureValidatingHttpServer.java:28)
        at com.bazaarvoice.auth.hmac.client.ValidatingHttpServer.handle(ValidatingHttpServer.java:50)
        at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121)
        at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 4.623 sec <<< FAILURE! - in com.bazaarvoice.auth.hmac.client.HmacClientFilterTest
validateSignatureWhenThereIsNoContent(com.bazaarvoice.auth.hmac.client.HmacClientFilterTest)  Time elapsed: 2.808 sec  <<< ERROR!

com.sun.jersey.api.client.UniformInterfaceException: GET http://localhost:1112?apiKey=someApiKey returned a response status of 500 Internal Server Error
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)
        at com.sun.jersey.api.client.WebResource.get(WebResource.java:191)
        at com.bazaarvoice.auth.hmac.client.HmacClientFilterTest.validateSignatureWhenThereIsNoContent(HmacClientFilterTest.java:127)

validateSignatureWhenContentIsPojo(com.bazaarvoice.auth.hmac.client.HmacClientFilterTest)  Time elapsed: 0.765 sec  <<< ERROR!
com.sun.jersey.api.client.UniformInterfaceException: PUT http://localhost:1113?passkey=someApiKey returned a response status of 500 Internal Server Error
        at com.sun.jersey.api.client.WebResource.voidHandle(WebResource.java:707)
        at com.sun.jersey.api.client.WebResource.access$400(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:522)
        at com.bazaarvoice.auth.hmac.client.HmacClientFilterTest.validateSignatureWhenContentIsPojo(HmacClientFilterTest.java:160)

validateSignatureWhenContentIsBinary(com.bazaarvoice.auth.hmac.client.HmacClientFilterTest)  Time elapsed: 0.278 sec  <<< ERROR!
com.sun.jersey.api.client.UniformInterfaceException: PUT http://localhost:1114?passkey=someApiKey returned a response status of 500 Internal Server Error
        at com.sun.jersey.api.client.WebResource.voidHandle(WebResource.java:707)
        at com.sun.jersey.api.client.WebResource.access$400(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:522)
        at com.bazaarvoice.auth.hmac.client.HmacClientFilterTest.validateSignatureWhenContentIsBinary(HmacClientFilterTest.java:194)

Results :

Tests in error:
  HmacClientFilterTest.validateSignatureWhenThereIsNoContent:127 » UniformInterface
  HmacClientFilterTest.validateSignatureWhenContentIsPojo:160 » UniformInterface
  HmacClientFilterTest.validateSignatureWhenContentIsBinary:194 » UniformInterface

It seems an exception in com.sun.jersey.api.client.UniformInterfaceException caused this error.
Can you tell me how to solve this issue? Thanks.

**Comment by srapp** [comment]
Hi @xiaodaxia .  It looks like there is a compatibility issue in the library we use in our client tests as it's behaving differently between JDK 7 and 8.  I'll have a patch out probably by the end of the week to fix the problem.  In the meantime, if you're just trying to get the project to build, you can skip the tests like this:
```
mvn clean install -DskipTests
```
